Repository kubernetes-sigs/cluster-inventory-api, pull requests merged in 2025-03, with the labels that each got.

#14 chore: Update dependencies
  go.mod
  go.sum
Labels: lgtm, cncf-cla: yes, approved, size/L

#16 Add the last observed time to the property API
  Makefile
  apis/v1alpha1/clusterprofile_types.go
  apis/v1alpha1/zz_generated.deepcopy.go
  config/crd/bases/multicluster.x-k8s.io_clusterprofiles.yaml
Labels: lgtm, cncf-cla: yes, approved, size/M

#15 Add SchemeGroupVersionKind and SchemeGroupVersionResource
  apis/v1alpha1/groupversion_info.go
Labels: lgtm, cncf-cla: yes, approved, size/S
